### ISSUE TITLE
execjs is bugging

### ISSUE THREAD

**Issue by VSCODE-0000** [xtekky/TikTok-Report-Bot#19]
ChatGPT cant even help me fix it

"It looks like you are running a Python script that is using the execjs library, which is a JavaScript interpreter for Python. The error message you are encountering is a ProgramError, which means that an error was encountered while executing JavaScript code through the execjs library.

Specifically, the error message says: "SyntaxError: Expected ';'". This error occurs because JavaScript requires semicolons (;) to separate statements, and it looks like there is a missing semicolon somewhere in the code.

You should try to locate the line of code that is causing this error and add the missing semicolon. This should resolve the issue and allow your script to run successfully."

"PS C:\Users\\Desktop\TikTok-Report-Bot-main>  c:; cd 'c:\Users\\Desktop\TikTok-Report-Bot-main'; & 'C:\Program Files\Python311\python.exe' 'c:\Users\\.vscode\extensions\ms-python.python-2023.2.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '54363' '--' 'c:\Users\\Desktop\TikTok-Report-Bot-main\main.py' 
Traceback (most recent call last):
  File "c:\Users\\Desktop\TikTok-Report-Bot-main\main.py", line 60, in <module>
    TikReport(cookies).start(username)
  File "c:\Users\\Desktop\TikTok-Report-Bot-main\main.py", line 47, in start
    this.userInfo = Api(cookies = this.cookies).user_info(username).json()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\\Desktop\TikTok-Report-Bot-main\utils\api.py", line 111, in user_info
    return this.client.get(f'https://www.tiktok.com/api/user/detail/?{this.sign(params, this.userAgent)}', headers = this.get_headers(), cookies = this.cookies)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\\Desktop\TikTok-Report-Bot-main\utils\api.py", line 39, in sign
    return params + '&X-Bogus=' + this.signer.call('sign', params, ua)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Roaming\Python\Python311\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Roaming\Python\Python311\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Roaming\Python\Python311\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Roaming\Python\Python311\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Roaming\Python\Python311\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Roaming\Python\Python311\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: Expected ';'
PS C:\Users\\Desktop\TikTok-Report-Bot-main> "

**Comment by xtekky** [comment]
do u have node installed on ur computer ?

**Comment by xtekky** [comment]
I can make a version with a localhost api

**Comment by VSCODE-0000** [comment]
> do u have node installed on ur computer ?

ok I installed node and it works now, but it just randomly opens and starts reporting a user, I diidnt even give it the name... just just starts reporting.
![image](https://user-images.githubusercontent.com/110119537/217834787-34283689-d441-485a-9a91-dba8aaed1151.png)

**Comment by VSCODE-0000** [comment]
reported: user - 9101 - {'now': 1675951517000, 'fatal_item_ids': [], 'logid': '202302091405165C85F3CE5E80562251FB'}
reported: user - 91011 - {'now': 1675951517000, 'fatal_item_ids': [], 'logid': '20230209140516AE65C534811DF1230FDF'}
reported: user - 9009 - {'now': 1675951518000, 'fatal_item_ids': [], 'logid': '20230209140517632B9EC1BF39B02076A5'}
reported: user - 90093 - {'now': 1675951518000, 'fatal_item_ids': [], 'logid': '20230209140517580CA435FFF6EB2322E1'}
reported: user - 90097 - {'now': 1675951518000, 'fatal_item_ids': [], 'logid': '2023020914051745E40DD15730FB211575'}
reported: user - 90095 - {'logid': '20230209140517AE65C534811DF123108A', 'now': 1675951518000, 'fatal_item_ids': []}
reported: user - 90064 - {'now': 1675951519000, 'fatal_item_ids': [], 'logid': '2023020914051848C12A8BD4DD2A225577'}
reported: user - 90061 - {'now': 1675951519000, 'fatal_item_ids': [], 'logid': '20230209140518D99FD78DEE1489221D85'}
reported: user - 90063 - {'now': 1675951519000, 'fatal_item_ids': [], 'logid': '20230209140518A121752A5D646B22DC30'}
reported: user - 9006 - {'now': 1675951519000, 'fatal_item_ids': [], 'logid': '20230209140518AE65C534811DF1231154'}
reported: user - 9008 - {'logid': '202302091405191C0CCF6B7C1F34220F70', 'now': 1675951520000, 'fatal_item_ids': []}
reported: user - 90081 - {'now': 1675951520000, 'fatal_item_ids': [], 'logid': '20230209140519B8532317939A1A227D30'}
reported: user - 90082 - {'now': 1675951520000, 'fatal_item_ids': [], 'logid': '202302091405193F8748C6942234214243'}
reported: user - 9007 - {'now': 1675951520000, 'fatal_item_ids': [], 'logid': '20230209140519AE65C534811DF1231212'}
reported: user - 1001 - {'now': 1675951521000, 'fatal_item_ids': [], 'logid': '2023020914051948C12A8BD4DD2A22568C'}

reported: user - 9101 - {'now': 1675951666000, 'fatal_item_ids': [], 'logid': '20230209140745FDB75E1819CFE72284CB'}
reported: user - 91011 - {'now': 1675951667000, 'fatal_item_ids': [], 'logid': '2023020914074683C897C09FEBAF2271FB'}
reported: user - 9009 - {'fatal_item_ids': [], 'logid': '20230209140746CC33F8C4582CC1222E72', 'now': 1675951667000}
reported: user - 90093 - {'fatal_item_ids': [], 'logid': '20230209140746BC138A401CD9C12344C9', 'now': 1675951667000}
reported: user - 90097 - {'logid': '20230209140746FDB75E1819CFE7228550', 'now': 1675951667000, 'fatal_item_ids': []}
reported: user - 90095 - {'now': 1675951667000, 'fatal_item_ids': [], 'logid': '2023020914074683C897C09FEBAF22727F'}
reported: user - 90064 - {'now': 1675951668000, 'fatal_item_ids': [], 'logid': '20230209140747BC138A401CD9C1234514'}
reported: user - 90061 - {'fatal_item_ids': [], 'logid': '20230209140747BC138A401CD9C1234530', 'now': 1675951668000}
reported: user - 90063 - {'now': 1675951668000, 'fatal_item_ids': [], 'logid': '20230209140747FDB75E1819CFE72285C8'}
reported: user - 9006 - {'now': 1675951668000, 'fatal_item_ids': [], 'logid': '2023020914074783C897C09FEBAF227320'}
reported: user - 9008 - {'now': 1675951669000, 'fatal_item_ids': [], 'logid': '20230209140748BC138A401CD9C1234585'}
reported: user - 90081 - {'now': 1675951669000, 'fatal_item_ids': [], 'logid': '20230209140748B91813B62135E2229DB0'}
reported: user - 90082 - {'logid': '20230209140748FDB75E1819CFE7228637', 'now': 1675951669000, 'fatal_item_ids': []}
reported: user - 9007 - {'now': 1675951669000, 'fatal_item_ids': [], 'logid': '202302091407485C146F62F21AFE2386F3'}
reported: user - 1001 - {'logid': '20230209140748BC138A401CD9C12345D3', 'now': 1675951669000, 'fatal_item_ids': []}
reported: user - 1002 - {'now': 1675951670000, 'fatal_item_ids': [], 'logid': '20230209140749B91813B62135E2229E3C'}
reported: user - 1003 - {'now': 1675951670000, 'fatal_item_ids': [], 'logid': '20230209140749FDB75E1819CFE72286B4'}
reported: user - 1004 - {'now': 1675951670000, 'fatal_item_ids': [], 'logid': '202302091407495C146F62F21AFE23878C'}
reported: user - 9002 - {'now': 1675951670000, 'fatal_item_ids': [], 'logid': '20230209140749B91813B62135E2229E90'}
reported: user - 90011 - {'now': 1675951670000, 'fatal_item_ids': [], 'logid': '2023020914074995FACA20DF577C2349E5'}
reported: user - 90010 - {'now': 1675951671000, 'fatal_item_ids': [], 'logid': '20230209140750FDB75E1819CFE7228745'}
reported: user - 9001 - {'now': 1675951671000, 'fatal_item_ids': [], 'logid': '2023020914075085B242E391E66F21DFB5'}
reported: user - 9010 - {'now': 1675951671000, 'fatal_item_ids': [], 'logid': '2023020914075085B242E391E66F21DFD3'}
reported: user - 9011 - {'fatal_item_ids': [], 'logid': '202302091407500E0648876190F2227AFE', 'now': 1675951672000}
reported: user - 90112 - {'now': 1675951672000, 'fatal_item_ids': [], 'logid': '202302091407517523625544E4F423C1A5'}
reported: user - 90113 - {'logid': '20230209140751941BC46F88C30D230100', 'now': 1675951672000, 'fatal_item_ids': []}
reported: user - 9003 - {'now': 1675951672000, 'fatal_item_ids': [], 'logid': '202302091407517D6F3623581D0C2298F2'}
reported: user - 90031 - {'now': 1675951672000, 'fatal_item_ids': [], 'logid': '20230209140751285C43FAB9EFC7217C67'}
reported: user - 90032 - {'fatal_item_ids': [], 'logid': '202302091407527523625544E4F423C24C', 'now': 1675951673000}
reported: user - 90033 - {'now': 1675951673000, 'fatal_item_ids': [], 'logid': '20230209140752941BC46F88C30D23018F'}
reported: user - 90034 - {'now': 1675951673000, 'fatal_item_ids': [], 'logid': '2023020914075206B57D4B3FD04C237B44'}
reported: user - 90035 - {'now': 1675951673000, 'fatal_item_ids': [], 'logid': '202302091407527523625544E4F423C2C1'}
reported: user - 90036 - {'now': 1675951674000, 'fatal_item_ids': [], 'logid': '20230209140753EA33F8BC0894A4243189'}
reported: user - 9004 - {'now': 1675951674000, 'fatal_item_ids': [], 'logid': '20230209140753941BC46F88C30D23022E'}
reported: user - 9005 - {'fatal_item_ids': [], 'logid': '202302091407539BCB0A940015F0228BEF', 'now': 1675951674000}
reported: user - 9012 - {'now': 1675951674000, 'fatal_item_ids': [], 'logid': '202302091407537523625544E4F423C345'}
reported: user - 910121 - {'fatal_item_ids': [], 'logid': '2023020914075475C0FF443FF7D0223C18', 'now': 1675951675000}
reported: user - 910122 - {'now': 1675951675000, 'fatal_item_ids': [], 'logid': '2023020914075485B242E391E66F21E20D'}
reported: user - 91012 - {'now': 1675951675000, 'fatal_item_ids': [], 'logid': '202302091407540E0648876190F2227C3C'}
reported: user - 91013 - {'now': 1675951675000, 'fatal_item_ids': [], 'logid': '2023020914075485B242E391E66F21E25E'}
reported: user - 910131 - {'now': 1675951676000, 'fatal_item_ids': [], 'logid': '20230209140755941BC46F88C30D230339'}
reported: user - 910132 - {'fatal_item_ids': [], 'logid': '202302091407555180650012A639220AEB', 'now': 1675951676000}
reported: user - 910133 - {'logid': '202302091407550E0648876190F2227C89', 'now': 1675951676000, 'fatal_item_ids': []}
reported: user - 910134 - {'fatal_item_ids': [], 'logid': '20230209140755BC138A401CD9C12348BA', 'now': 1675951676000}
reported: user - 910135 - {'now': 1675951676000, 'fatal_item_ids': [], 'logid': '202302091407550E0648876190F2227CA7'}
reported: user - 91014 - {'fatal_item_ids': [], 'logid': '20230209140756941BC46F88C30D2303DE', 'now': 1675951677000}
reported: user - 9013 - {'now': 1675951677000, 'fatal_item_ids': [], 'logid': '2023020914075675C0FF443FF7D0223D02'}
reported: user - 9102 - {'logid': '2023020914075606B57D4B3FD04C237E48', 'now': 1675951677000, 'fatal_item_ids': []}
scraped: 33 videos
scraped: 66 videos
scraped: 99 videos
scraped: 132 videos
scraped: 154 videos
Exception in thread Thread-111 (reportVideo):
Exception in thread Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Thread-112 (reportVideo)Exception in thread :
Exception in thread Thread-113 (reportVideo):
Thread-114 (reportVideo)Traceback (most recent call last):
Exception in thread :
Traceback (most recent call last):

**Comment by grylld** [comment]
"C:\Users\Desktop\TikTok-Report-Bot-main\TikTok-Report-Bot-main\main.py", line 2, in <module>
    from utils.api       import Api
ModuleNotFoundError: No module named 'utils.api'

Looks like module file wont import.

**Comment by Tukzlol** [comment]
> 

change username on line 55
