### ISSUE TITLE
Not sure what I'm missing

### ISSUE THREAD

**Issue by clankie83** [xtekky/TikTok-Report-Bot#3]
Python and pip are installed, I tried a couple of thing but :
<img width="960" alt="Screenshot 2022-07-15 074910" src="https://user-images.githubusercontent.com/103049507/179159427-cf3065ac-0f03-47cd-994f-1ddf0eb607f1.png">

**Comment by xtekky** [comment]
you need to install python, if ur not blind and read it says it there

**Comment by clankie83** [comment]
Python and pip are already installed. Not blind.

**Comment by iCodeOfTruth** [comment]
Run in Command Promot not in Powershell

**Comment by xtekky** [comment]
@clankie83 did u solve the problem ?
